apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-room-booking-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-room-booking
  template:
    metadata:
      labels:
        app: meeting-room-booking
    spec:
      containers:
        - name: booking-ms
          image: meeting-room-booking/booking:v1.0.0
          env:
            - name: MONGODB_URI
              value: mongodb://root:password123@mongodb:27017/meetingBooking
            - name: RABBIT_MQ_URI
              value: amqp://rabbitmq:5672
          ports:
            - containerPort: 4000
