apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booking-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-ms
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
