// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Meeting room booking",
//   description: "",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import '@/app/globals.css';
// import Footer from '@app/components/Layout/Footer';
import Header from '@/components/Layout/Header';
// import { useServerAuthSession } from '@app/hooks/useServerAuthSession';

/**
 * Using force dynamic so changes in business assets (e.g. services) are immediately reflected.
 * If you prefer having it reflected only after redeploy (not recommended) please remove it
 * **/
export const revalidate = 0;

export default function RootLayout(
  layoutProps: Readonly<{
    children: React.ReactNode;
  }>
) {
  const { children } = layoutProps;
  // const wixSession = useServerAuthSession();
  return (
    <html lang="en">
      <head>
        <title>Create Wix Bookings Site</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Bookings integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>

      <body className="parallax-background">
        <Header/>
        <main className="bg-transparent min-h-[600px]">{children}</main>
        {/* <Footer /> */}
      </body>

      {/* <body className="">
          <main className="max-w-full-content mx-auto bg-gray-c2 pt-32">
            <h1>
              Page not available. Please add an environment variable called
              NEXT_PUBLIC_WIX_CLIENT_ID, containing the client ID, to your
              deployment provider.
            </h1>
          </main>
        </body> */}

    </html>
  );
}

